# This file was generated by GoReleaser. DO NOT EDIT.
cask "tld" do
  version "2.2.4"

  on_macos do
    on_intel do
      sha256 "295b3f0bc2436ec73decfe4ba8272e24217a4bbda7bbdf16114fcd4e195067b1"
      url "https://github.com/Mertcikla/tld/releases/download/v#{version}/tld_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "af21c5b9781c7cc0579b3e704ca3a88d1e1325651b4febf3b3ca4739f4fce14f"
      url "https://github.com/Mertcikla/tld/releases/download/v#{version}/tld_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "081fa3f2bd8478e68ca715498dc81404436db79feaf7b089d595b6448763e962"
      url "https://github.com/Mertcikla/tld/releases/download/v#{version}/tld_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a985edaff804fa45ad572347303e0e6fc60f084d7874fff118cf38305c315937"
      url "https://github.com/Mertcikla/tld/releases/download/v#{version}/tld_Linux_arm64.tar.gz"
    end
  end

  name "tld"
  desc "CLI for the tlDiagram architecture diagramming system"
  homepage "https://tldiagram.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tld"

  # No zap stanza required

end
