# This file was generated by GoReleaser. DO NOT EDIT.
cask "tld" do
  version "2.1.3"

  on_macos do
    on_intel do
      sha256 "823abd824b0285bae858647570b39829c80ec021ae2033d5047e5e4065e9e316"
      url "https://github.com/Mertcikla/tld/releases/download/v#{version}/tld_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5234b4a147f8fc990199143359875230aa8fca002decba5c1d5f03e1a5e268b5"
      url "https://github.com/Mertcikla/tld/releases/download/v#{version}/tld_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3e984e37607030430226eda04c3ae4483b50f58176b39a0da216ab995e7a4104"
      url "https://github.com/Mertcikla/tld/releases/download/v#{version}/tld_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7a7ef3f6d5994c344c8077c3d6c6e9bd4aeb93c484e17ce3f7ad0df3f22741a5"
      url "https://github.com/Mertcikla/tld/releases/download/v#{version}/tld_Linux_arm64.tar.gz"
    end
  end

  name "tld"
  desc "CLI for the tlDiagram architecture diagramming system"
  homepage "https://tldiagram.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tld"

  # No zap stanza required

end
