# This file was generated by GoReleaser. DO NOT EDIT.
cask "tld" do
  version "2.2.0-alpha.2"

  on_macos do
    on_intel do
      sha256 "99b5377ba54c5aaaa0c87265f9edeef659b3d91aa9a8d068ec2e82dc8aece6ec"
      url "https://github.com/Mertcikla/tld/releases/download/v#{version}/tld_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "06895f17728265951e62bc36d91cf21dbcaff649ccb8cca545c8b46930a07888"
      url "https://github.com/Mertcikla/tld/releases/download/v#{version}/tld_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "60fea0cdc1e568a4b967a954c60c797f4e109cf35a42982cec4dcb926f548bba"
      url "https://github.com/Mertcikla/tld/releases/download/v#{version}/tld_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "58057248e9c6ab7ee4f7c66bbd9fc3106fb7d182541815ed746cdd9e8ba2ddcf"
      url "https://github.com/Mertcikla/tld/releases/download/v#{version}/tld_Linux_arm64.tar.gz"
    end
  end

  name "tld"
  desc "CLI for the tlDiagram architecture diagramming system"
  homepage "https://tldiagram.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tld"

  # No zap stanza required

end
