# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tld < Formula
  desc "CLI for the tlDiagram architecture diagramming system"
  homepage "https://tldiagram.com"
  version "0.1.6-beta.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Mertcikla/tld-cli/releases/download/v0.1.6-beta.1/tld_Darwin_x86_64.tar.gz"
      sha256 "5d7ea916923fd9d4c7d3bae0474592f0b95dff6f071cae302e3be612caa986db"

      define_method(:install) do
        bin.install "tld"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Mertcikla/tld-cli/releases/download/v0.1.6-beta.1/tld_Darwin_arm64.tar.gz"
      sha256 "464bc3a9897d50d966dc2cfeb2e9fa45560756cf4fd368b0c5a4252165ad30c9"

      define_method(:install) do
        bin.install "tld"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mertcikla/tld-cli/releases/download/v0.1.6-beta.1/tld_Linux_x86_64.tar.gz"
      sha256 "0c80055e6196a12570a8220a63a3dda3e11b756ad189c895b58bbce47f7de943"
      define_method(:install) do
        bin.install "tld"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mertcikla/tld-cli/releases/download/v0.1.6-beta.1/tld_Linux_arm64.tar.gz"
      sha256 "66dfe0f21bef90c2e316657e09a77faee3455ab1b337cd9a61d7049974966ce2"
      define_method(:install) do
        bin.install "tld"
      end
    end
  end

  test do
    system "#{bin}/tld version"
  end
end
