# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tld < Formula
  desc "CLI for the tlDiagram architecture diagramming system"
  homepage "https://tldiagram.com"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Mertcikla/tld-cli/releases/download/v0.1.7/tld_Darwin_x86_64.tar.gz"
      sha256 "cee7788ad38d26d32ad5a963baa6cf6e568b779d333ad1e74e1fcef0c92cca21"

      define_method(:install) do
        bin.install "tld"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Mertcikla/tld-cli/releases/download/v0.1.7/tld_Darwin_arm64.tar.gz"
      sha256 "9355dcafbbfe4234f947ed523d85496d989f2a0501b2fb3056fd8eab7a19a25d"

      define_method(:install) do
        bin.install "tld"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mertcikla/tld-cli/releases/download/v0.1.7/tld_Linux_x86_64.tar.gz"
      sha256 "25e1d7c2631018cc4a45aadc0529cc7ec2294a46f0f9def0f4d02fb445eb4dee"
      define_method(:install) do
        bin.install "tld"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mertcikla/tld-cli/releases/download/v0.1.7/tld_Linux_arm64.tar.gz"
      sha256 "479de77bb0a589c326e2f095c998f200670eaecf980308b6b5c877bc0656b2d7"
      define_method(:install) do
        bin.install "tld"
      end
    end
  end

  test do
    system "#{bin}/tld version"
  end
end
